### ISSUE TITLE
code-server cannot use curl to request (Web browser open-vsx.org)

### ISSUE THREAD

**Issue by Alan3344** [Huachao/vscode-restclient#1321]
- REST Client Version: v0.26.0
- VSCode Version: v4.95.1
- OS Version: Windows 11 professional 24H2 / Google Chrome: 130.0.6723.117 (Official Build) (64-bit) (cohort: Stable) 

Steps to Reproduce:

1. Install code-server using docker
2. Open code-server in a web browser
3. Search and install the plugin `rest-client`
4. Open a folder and create a new `curl.http` file
5. Click `Send Request`
6. A prompt will pop up: `u.default is not a function`

[Reference plugin link](https://open-vsx.org/extension/humao/rest-client)

The latest version of Vscode client can work normally
```
Version: 1.95.1 (user setup)
Commit: 65edc4939843c90c34d61f4ce11704f09d3e5cb6
Date: 2024-10-31T05:14:54.222Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.26100
```

<details>
<summary>Installation Details</summary>

```
docker run -it -p 45001:8080 -v //d/mycode:/home/coder/mycode:rw --name code-server codercom/code-server:latest
```

```
code-server: v4.95.1
Code: 1.95.1
Commit: 952523f288b1351f622a19507eb699b97c1d6410
Date: 2024-11-01T21:10:15.854Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
```

![image](https://github.com/user-attachments/assets/7894783d-d1c6-4887-919b-ae37c7d07514)

![image](https://github.com/user-attachments/assets/c633b6b2-2b2f-4c88-a358-5aa4b1ef11a8)

![image](https://github.com/user-attachments/assets/3a29fda8-96cc-4289-b6e0-713b19cba55c)
</details>

**Comment by Alan3344** [comment]
Extension Host (Remote) logs:
No logs in `REST` output window
![image](https://github.com/user-attachments/assets/7afb03f8-2cf2-424f-bf36-395d883c123b)

**Comment by mbnoimi** [comment]
I've exactly the same issue under Linux Mint:

```
Name: REST Client
Id: humao.rest-client
Description: REST Client for Visual Studio Code
Version: 0.26.0
Publisher: humao
VS Marketplace Link: https://open-vsx.org/vscode/item?itemName=humao.rest-client
```

Requested link works fine using terminal:

```bash
curl -X POST \
  http://localhost:5050/auth/login \
  -H 'Content-Type: application/json' \
  -d '{"username": "admin", "password": "admin"}'
  ```

**Comment by robertcristianoo** [comment]
after upgrading php 8.2 to 8.4 i started seen this error too.

**Comment by chenmijiang** [comment]
i have same problem

**Comment by madbonez** [comment]
me too. macos ventura and cursor

ERR u.default is not a function: TypeError: u.default is not a function
	at p.parseHttpRequest (/Users/ad/.cursor/extensions/humao.rest-client-0.26.0-universal/dist/extension.js:2:1947156)
	at t.HttpDocumentSymbolProvider.getRequestSymbolInfo (/Users/ad/.cursor/extensions/humao.rest-client-0.26.0-universal/dist/extension.js:2:1932507)
	at async t.HttpDocumentSymbolProvider.provideDocumentSymbols (/Users/ad/.cursor/extensions/humao.rest-client-0.26.0-universal/dist/extension.js:2:1932030)
	at async NLe.provideDocumentSymbols (file:///Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:161:1529928) TypeError: u.default is not a function
